# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Efficient Cause
tagline:             'Exploring data and showing how'
description:         'A blog aimed at exploring interesting data, discovering the core forces that explain it, and explaining how it was done.'
url:                 seanryjohnston.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sean Johnston
  url:               
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
