# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Sean Johnston
tagline:             'Data Analyst'
description:         'A blog aimed at exploring interesting data, discovering the core forces that explain it, and explaining how it was done.'
url:                 seanryjohnston.github.io
baseurl:             'blog/'
paginate:            5

# About/contact
author:
  name:              Sean Johnston
  url:               
  email:             

# Custom vars
version:             1.0.0
